language: ruby
cache: bundler
gemfile: Gemfile
script:
  - bundle exec jekyll build
branches:
  only:
    # Change this to gh-pages if you're deploying using the gh-pages branch
    - master
rvm:
 - 2.4
deploy:
 provider: s3
 access_key_id: $AWS_ACCESS_KEY_ID
 secret_access_key: $AWS_SECRET_ACCESS_KEY
 bucket: $AWS_BUCKET_NAME
 skip_cleanup: true
 region: $AWS_REGION
 local_dir: _site
 on:
  branch: master
