# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Avocats Palud à Lausanne
email: loicgasser4@gmail.com
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://avocats-palud-demo.s3-website.eu-central-1.amazonaws.com" # "http://www.avocats-palud.ch" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
theme: minimal-mistakes-jekyll
minimal_mistakes_skin: "contrast"

locale: "fr-CH"
name: "Avocats Palud à Lausanne"
description: "L'Etude Avocats-Palud à Lausanne et Morges avec Me Diego Bischof, Me Marie-Pomme Moinat, Me Sofia Arsénio et Me David Moinat, avocats, présente ses services. Droit pénal, droit civil, droit de la construction et de l’aménagement du territoire, droit des étrangers, droit de la famille et du divorce, droit de l'aide aux victimes d'infraction (LAVI), droit du travail, droit des étrangers, droit des assurances sociales, droit des contrats d'entreprise et du mandat, droit du sport, des sociétés, des établissements publics."
teaser: "/assets/logo-avocats-palud.jpg"

collection:
  avocats:
    collections_dir: assets

defaults:
  # _docs
  - scope:
      path: ""
      type: docs
    values:
      sidebar:
        nav: "docs"

production: false

compress_html:
  clippings: all
  ignore:
    envs: development

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
